// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: podcertbroker.proto

package podcertbrokerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignerPurpose selects which CA pool signs the certificate and which
// identity/SAN policy the server applies. The caller cannot influence that
// policy beyond selecting one of these — see MintPodCertificateRequest.
type SignerPurpose int32

const (
	SignerPurpose_SIGNER_PURPOSE_UNSPECIFIED SignerPurpose = 0
	// podidentity.podcert.ate.dev/identity: a PodIdentity certificate (see
	// internal/substratex509), scoped to the caller's own namespace, service
	// account, pod, and node.
	SignerPurpose_SIGNER_PURPOSE_POD_IDENTITY SignerPurpose = 1
	// servicedns.podcert.ate.dev/identity: a serving certificate whose DNS SANs
	// are derived from the Services that select the caller's pod.
	SignerPurpose_SIGNER_PURPOSE_SERVICE_DNS SignerPurpose = 2
)

// Enum value maps for SignerPurpose.
var (
	SignerPurpose_name = map[int32]string{
		0: "SIGNER_PURPOSE_UNSPECIFIED",
		1: "SIGNER_PURPOSE_POD_IDENTITY",
		2: "SIGNER_PURPOSE_SERVICE_DNS",
	}
	SignerPurpose_value = map[string]int32{
		"SIGNER_PURPOSE_UNSPECIFIED":  0,
		"SIGNER_PURPOSE_POD_IDENTITY": 1,
		"SIGNER_PURPOSE_SERVICE_DNS":  2,
	}
)

func (x SignerPurpose) Enum() *SignerPurpose {
	p := new(SignerPurpose)
	*p = x
	return p
}

func (x SignerPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignerPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_podcertbroker_proto_enumTypes[0].Descriptor()
}

func (SignerPurpose) Type() protoreflect.EnumType {
	return &file_podcertbroker_proto_enumTypes[0]
}

func (x SignerPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignerPurpose.Descriptor instead.
func (SignerPurpose) EnumDescriptor() ([]byte, []int) {
	return file_podcertbroker_proto_rawDescGZIP(), []int{0}
}

type MintPodCertificateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bound ServiceAccount token (JWT) from a projected serviceAccountToken
	// volume, audience-scoped to this broker. TokenReview against this token is
	// the caller's authentication; pod_name/pod_uid below are a claim the
	// server cross-checks against a live Pod lookup (and, when present, the
	// token's own bound-object claims) rather than trusting outright. This is
	// strictly weaker than PodCertificateRequest's kubelet/NodeRestriction
	// attestation: it is API-server-reported identity, not kubelet-attested.
	Token   string        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Purpose SignerPurpose `protobuf:"varint,2,opt,name=purpose,proto3,enum=podcertbroker.SignerPurpose" json:"purpose,omitempty"`
	// DER-encoded PKCS#10 certificate signing request. Only its public key is
	// used — any Subject or SAN fields the caller populated are ignored. The
	// issued certificate's identity is built entirely server-side from
	// TokenReview plus a Pod (and, for SIGNER_PURPOSE_POD_IDENTITY, Node)
	// lookup, never from the CSR.
	CertificateSigningRequest []byte `protobuf:"bytes,3,opt,name=certificate_signing_request,json=certificateSigningRequest,proto3" json:"certificate_signing_request,omitempty"`
	// The caller's own claim of which pod it is, sourced from the Downward
	// API. Never trusted on its own — see the token field comment above.
	PodName       string `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid        string `protobuf:"bytes,5,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintPodCertificateRequest) Reset() {
	*x = MintPodCertificateRequest{}
	mi := &file_podcertbroker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintPodCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintPodCertificateRequest) ProtoMessage() {}

func (x *MintPodCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podcertbroker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintPodCertificateRequest.ProtoReflect.Descriptor instead.
func (*MintPodCertificateRequest) Descriptor() ([]byte, []int) {
	return file_podcertbroker_proto_rawDescGZIP(), []int{0}
}

func (x *MintPodCertificateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MintPodCertificateRequest) GetPurpose() SignerPurpose {
	if x != nil {
		return x.Purpose
	}
	return SignerPurpose_SIGNER_PURPOSE_UNSPECIFIED
}

func (x *MintPodCertificateRequest) GetCertificateSigningRequest() []byte {
	if x != nil {
		return x.CertificateSigningRequest
	}
	return nil
}

func (x *MintPodCertificateRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *MintPodCertificateRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

type MintPodCertificateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DER-encoded leaf certificate followed by any intermediates, leaf first.
	CertificateChain [][]byte `protobuf:"bytes,1,rep,name=certificate_chain,json=certificateChain,proto3" json:"certificate_chain,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MintPodCertificateResponse) Reset() {
	*x = MintPodCertificateResponse{}
	mi := &file_podcertbroker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintPodCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintPodCertificateResponse) ProtoMessage() {}

func (x *MintPodCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podcertbroker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintPodCertificateResponse.ProtoReflect.Descriptor instead.
func (*MintPodCertificateResponse) Descriptor() ([]byte, []int) {
	return file_podcertbroker_proto_rawDescGZIP(), []int{1}
}

func (x *MintPodCertificateResponse) GetCertificateChain() [][]byte {
	if x != nil {
		return x.CertificateChain
	}
	return nil
}

var File_podcertbroker_proto protoreflect.FileDescriptor

const file_podcertbroker_proto_rawDesc = "" +
	"\n" +
	"\x13podcertbroker.proto\x12\rpodcertbroker\"\xdd\x01\n" +
	"\x19MintPodCertificateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x126\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1c.podcertbroker.SignerPurposeR\apurpose\x12>\n" +
	"\x1bcertificate_signing_request\x18\x03 \x01(\fR\x19certificateSigningRequest\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\x05 \x01(\tR\x06podUid\"I\n" +
	"\x1aMintPodCertificateResponse\x12+\n" +
	"\x11certificate_chain\x18\x01 \x03(\fR\x10certificateChain*p\n" +
	"\rSignerPurpose\x12\x1e\n" +
	"\x1aSIGNER_PURPOSE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSIGNER_PURPOSE_POD_IDENTITY\x10\x01\x12\x1e\n" +
	"\x1aSIGNER_PURPOSE_SERVICE_DNS\x10\x022\x83\x01\n" +
	"\x14PodCertificateBroker\x12k\n" +
	"\x12MintPodCertificate\x12(.podcertbroker.MintPodCertificateRequest\x1a).podcertbroker.MintPodCertificateResponse\"\x00BEZCgithub.com/agent-substrate/substrate/internal/proto/podcertbrokerpbb\x06proto3"

var (
	file_podcertbroker_proto_rawDescOnce sync.Once
	file_podcertbroker_proto_rawDescData []byte
)

func file_podcertbroker_proto_rawDescGZIP() []byte {
	file_podcertbroker_proto_rawDescOnce.Do(func() {
		file_podcertbroker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podcertbroker_proto_rawDesc), len(file_podcertbroker_proto_rawDesc)))
	})
	return file_podcertbroker_proto_rawDescData
}

var file_podcertbroker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_podcertbroker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_podcertbroker_proto_goTypes = []any{
	(SignerPurpose)(0),                 // 0: podcertbroker.SignerPurpose
	(*MintPodCertificateRequest)(nil),  // 1: podcertbroker.MintPodCertificateRequest
	(*MintPodCertificateResponse)(nil), // 2: podcertbroker.MintPodCertificateResponse
}
var file_podcertbroker_proto_depIdxs = []int32{
	0, // 0: podcertbroker.MintPodCertificateRequest.purpose:type_name -> podcertbroker.SignerPurpose
	1, // 1: podcertbroker.PodCertificateBroker.MintPodCertificate:input_type -> podcertbroker.MintPodCertificateRequest
	2, // 2: podcertbroker.PodCertificateBroker.MintPodCertificate:output_type -> podcertbroker.MintPodCertificateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_podcertbroker_proto_init() }
func file_podcertbroker_proto_init() {
	if File_podcertbroker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podcertbroker_proto_rawDesc), len(file_podcertbroker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podcertbroker_proto_goTypes,
		DependencyIndexes: file_podcertbroker_proto_depIdxs,
		EnumInfos:         file_podcertbroker_proto_enumTypes,
		MessageInfos:      file_podcertbroker_proto_msgTypes,
	}.Build()
	File_podcertbroker_proto = out.File
	file_podcertbroker_proto_goTypes = nil
	file_podcertbroker_proto_depIdxs = nil
}
