// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: podcertbroker.proto

package podcertbrokerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodCertificateBroker_MintPodCertificate_FullMethodName = "/podcertbroker.PodCertificateBroker/MintPodCertificate"
)

// PodCertificateBrokerClient is the client API for PodCertificateBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PodCertificateBroker mints the same podidentity/servicedns certificates
// podcertcontroller issues via PodCertificateRequest, for clusters where that
// Kubernetes API is unavailable (its ClusterTrustBundle/PodCertificateRequest
// feature gates are not exposed on a managed control plane).
//
// Called by a per-pod sidecar in place of the kubelet-managed podCertificate
// projected volume. Identity is established by TokenReview against a bound
// ServiceAccount token, not by kubelet/NodeRestriction attestation, so it is
// a weaker binding than PodCertificateRequest gives: see the caller-identity
// comment on MintPodCertificateRequest.
type PodCertificateBrokerClient interface {
	MintPodCertificate(ctx context.Context, in *MintPodCertificateRequest, opts ...grpc.CallOption) (*MintPodCertificateResponse, error)
}

type podCertificateBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewPodCertificateBrokerClient(cc grpc.ClientConnInterface) PodCertificateBrokerClient {
	return &podCertificateBrokerClient{cc}
}

func (c *podCertificateBrokerClient) MintPodCertificate(ctx context.Context, in *MintPodCertificateRequest, opts ...grpc.CallOption) (*MintPodCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintPodCertificateResponse)
	err := c.cc.Invoke(ctx, PodCertificateBroker_MintPodCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodCertificateBrokerServer is the server API for PodCertificateBroker service.
// All implementations must embed UnimplementedPodCertificateBrokerServer
// for forward compatibility.
//
// PodCertificateBroker mints the same podidentity/servicedns certificates
// podcertcontroller issues via PodCertificateRequest, for clusters where that
// Kubernetes API is unavailable (its ClusterTrustBundle/PodCertificateRequest
// feature gates are not exposed on a managed control plane).
//
// Called by a per-pod sidecar in place of the kubelet-managed podCertificate
// projected volume. Identity is established by TokenReview against a bound
// ServiceAccount token, not by kubelet/NodeRestriction attestation, so it is
// a weaker binding than PodCertificateRequest gives: see the caller-identity
// comment on MintPodCertificateRequest.
type PodCertificateBrokerServer interface {
	MintPodCertificate(context.Context, *MintPodCertificateRequest) (*MintPodCertificateResponse, error)
	mustEmbedUnimplementedPodCertificateBrokerServer()
}

// UnimplementedPodCertificateBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodCertificateBrokerServer struct{}

func (UnimplementedPodCertificateBrokerServer) MintPodCertificate(context.Context, *MintPodCertificateRequest) (*MintPodCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintPodCertificate not implemented")
}
func (UnimplementedPodCertificateBrokerServer) mustEmbedUnimplementedPodCertificateBrokerServer() {}
func (UnimplementedPodCertificateBrokerServer) testEmbeddedByValue()                              {}

// UnsafePodCertificateBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodCertificateBrokerServer will
// result in compilation errors.
type UnsafePodCertificateBrokerServer interface {
	mustEmbedUnimplementedPodCertificateBrokerServer()
}

func RegisterPodCertificateBrokerServer(s grpc.ServiceRegistrar, srv PodCertificateBrokerServer) {
	// If the following call panics, it indicates UnimplementedPodCertificateBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodCertificateBroker_ServiceDesc, srv)
}

func _PodCertificateBroker_MintPodCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintPodCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodCertificateBrokerServer).MintPodCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodCertificateBroker_MintPodCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodCertificateBrokerServer).MintPodCertificate(ctx, req.(*MintPodCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodCertificateBroker_ServiceDesc is the grpc.ServiceDesc for PodCertificateBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodCertificateBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podcertbroker.PodCertificateBroker",
	HandlerType: (*PodCertificateBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintPodCertificate",
			Handler:    _PodCertificateBroker_MintPodCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podcertbroker.proto",
}
